
import React, { useState } from 'react';
import Button from 'react-bootstrap/Button';
import Modal from 'react-bootstrap/Modal';
// import sgmail from '@sendgrid/mail'
import { TiMediaEject } from 'react-icons/ti';
import Head from 'next/head'
import axios from 'axios'


function Downloader({ showExport, setExport, csv }) {
    

    const handleClose = () => setExport(false);
    const handleShow = () => setExport(true);
  console.log("before modal")

    const message = {
        to:"steven.segerlund@yahoo.com",
        from:"rmbar19@hotmail.com",
        subject:"Test4u",
        text:"Are you mommy or daddy?",
        attachments:[{
            content:"studentinfo.csv",
            filename:"Whipmyhairbackn4th.jpg",
            type:"straight",
            disposition:"you",
            snap:"buy a house, sign some papers, become an elf, sit on a shelf, email a pull request, H-A-R-D-E-R mommy isn't here today"
        }]
    }
    return (
      <>
      
      {/* <button className="add-button" onClick={() => setExport(!showExport)}/> */}
        <Modal show={showExport} onHide={handleClose}>
          <Modal.Header closeButton>
            <Modal.Title>Modal heading</Modal.Title>
          </Modal.Header>
          <Modal.Body>
            <a href={"data:text/plain;charset=utf-8," + encodeURIComponent(csv)} download="studentinfo.csv">
                Email .csv
            </a>
            <a href={"data:text/plain;charset=utf-8," + encodeURIComponent(csv)} download="studentinfo.csv">
                Export .csv
            </a>
            </Modal.Body>
          {/* <Modal.Footer>
            <Button variant="secondary" onClick={handleClose}>
              Close
            </Button>
            <Button variant="primary" onClick={handleClose}>
              Save Changes
            </Button>
          </Modal.Footer> */}
        </Modal>
      </>
    );
}


 /////////////////////Below is sample code for creating email on your index.js. Source link:https://www.linkedin.com/pulse/how-send-email-next-js-app-module-zeel-prajapati/
 /////We need to integrate this with the working code above
// export default function Home() {
 
//  const [email,setEmail]=useState('')
//  const SendMail = async (e)=>{
//    e.preventDefault();
// console.log('call')
//  }
 
//  return (
//    <div className={styles.container}>
//      <Head>
//        <title>Create Next App</title>
//        <meta name="description" content="Generated by create next app" />
//        <link rel="icon" href="/favicon.ico" />
//      </Head>
    
 
//      <main className={styles.main}>
//        <form>
//       <input type="email" placeholder="Enter Mail" required value={email} onChange={(e)=>setEmail(e.target.value)}></input>
//       <button onClick={SendMail}>Send</button>
//         </form>
//      </main>
//    </div>
//  )
// }

export default Downloader;