
import React, { useState } from 'react';
import Modal from 'react-bootstrap/Modal';
import emailjs from '@emailjs/browser';


function Downloader({ showExport, setExport, csv, students }) {

  let studentString = ''
  const handleClose = () => setExport(false);


  function organizeStudents() {
    
    for (let i = 0; i < students.length; i++) {
      
      var temp = Object.values(students[i])
      studentString += JSON.stringify(temp) + '\n'
      

    }
    return studentString
  }
  return (
    <>
      <Modal show={showExport} onHide={handleClose}>
        <Modal.Header closeButton>
          <Modal.Title>Modal heading</Modal.Title>
        </Modal.Header>
        <Modal.Body>

          <a href={'#0'} onClick={
            () => {
              organizeStudents()
              emailjs.send('service_q7ydff5', 'template_eyggsr3', {message: studentString}, 'fVpXVYOcSjiWblEjw')
                .then((result) => {
                  alert("Email sent successfully!")
                }, (error) => {
                  alert("Unable to send email");
                });
            }
          }>
            Email .csv

          </a>
          <br></br>
          <a href={"data:text/plain;charset=utf-8," + encodeURIComponent(csv)} download="studentinfo.csv">
            Export .csv
          </a>
        </Modal.Body>
        {/* <Modal.Footer>
            <Button variant="secondary" onClick={handleClose}>
              Close
            </Button>
            <Button variant="primary" onClick={handleClose}>
              Save Changes
            </Button>
          </Modal.Footer> */}
      </Modal>
    </>
  );
}


/////////////////////Below is sample code for creating email on your index.js. Source link:https://www.linkedin.com/pulse/how-send-email-next-js-app-module-zeel-prajapati/
/////We need to integrate this with the working code above
// export default function Home() {

//  const [email,setEmail]=useState('')
//  const SendMail = async (e)=>{
//    e.preventDefault();
// console.log('call')
//  }

//  return (
//    <div className={styles.container}>
//      <Head>
//        <title>Create Next App</title>
//        <meta name="description" content="Generated by create next app" />
//        <link rel="icon" href="/favicon.ico" />
//      </Head>


//      <main className={styles.main}>
//        <form>
//       <input type="email" placeholder="Enter Mail" required value={email} onChange={(e)=>setEmail(e.target.value)}></input>
//       <button onClick={SendMail}>Send</button>
//         </form>
//      </main>
//    </div>
//  )
// }

export default Downloader;