import Head from 'next/head'
import Body from '../src/components/Body'

export default function Home() {
  return (
    <div>
      <Head>
        <title>BLUE OCEAN || ADMISSION</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Body />
    </div>
  )
}
